name: Manual Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment commit message'
        default: 'Manual deployment'
        required: true
        type: string
      merge_develop:
        description: 'Merge develop branch into master'
        default: true
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Fetch all branches
    run: git fetch --all

    - name: Merge develop into master and deploy
      if: ${{ inputs.merge_develop }}
      run: |
        git fetch origin
        git checkout master
        git merge origin/develop
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "${{ github.event.inputs.deploy_message }}"
        git push origin HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
